name: forces-gains
channels:
  - conda-forge
  - chrisroadmap
dependencies:
  - fair==2.1.0
  - jupyter
  - matplotlib
  - nbstripout
  - netCDF4
  - numpy
  - pandas
  - pooch
  - scipy
  - tqdm
  - xarray
